### ISSUE TITLE
closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

### ISSUE THREAD

**Issue by afckd** [google/closure-library#988] opened 2019-09-18 06:20 UTC
closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

**Comment by kjin** [comment] 2019-09-24 17:25
Can you elaborate on how you came across this issue? The line in question doesn't seem to have a syntax error: https://github.com/google/closure-library/blame/13a702155814c84950b16027035bf3e29d6fa5be/closure/goog/streams/full_test_cases.js#L635

**Comment by proxiaoyi** [comment] 2019-09-29 03:04
> closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

refer from csdn：（this work for me）
go run setup.go (this fails)
cd third_party/closure-library/
git reset --hard v20170409
cd -
go run setup.go (this passes)

**Comment by nreid260** [comment] 2019-10-03 22:20
Created Google internal issue b/142081541

**Comment by nreid260** [comment] 2019-10-03 22:24
@afckd We need more information to do anything about this issue

**Comment by lx610** [comment] 2019-10-10 07:02
i have the same problem:  closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected  .  And i solve the problem by using realse version before 2017 year.

**Comment by nreid260** [comment] 2019-10-10 17:03
What version of the compiler is reporting the parse error? Those tests (I think) use async functions and will need a parser that supports them.

**Comment by fudongbai** [comment] 2019-11-10 01:17
I upgraded to go1.13.4 and still has this issue:
go version go1.13.4 darwin/amd64

Could you tell what go version has parser support?

**Comment by fudongbai** [comment] 2019-11-10 01:45
I run into this issue by issuing 'go run setup.go' in battery-historian, this can be fixed by updating *closureCompilerVersion* in setup.go to 20191027, hope this will help people using battery-historian.

**Comment by mprobst** [comment] 2019-11-11 10:22
This is working as intended then, closing the issue. Please reopen if there's more here.

**Closed by mprobst** 2019-11-11 10:22 UTC
Labels: internal-issue-created
