### ISSUE TITLE
MD5 function implementation doesn't handle non-ASCII characters

### ISSUE THREAD

**Issue by dpashkevich** [google/closure-library#809] opened 2017-03-17 23:15 UTC
The implementation clips character codes to byte-length at some point, which causes collisions when non-ASCII characters are used in the input string.

Example:
```
function md5(string) {
   var hasher = new goog.crypt.Md5();
   hasher.reset();
   hasher.update(string);
   return goog.crypt.byteArrayToHex(hasher.digest());
}
md5('XXXD');
// "c98a24315085c0848a3762a3f2795ce8"
md5('XXXф');
//"c98a24315085c0848a3762a3f2795ce8"
```

Workaround I currently use:
```
function md5(string) {
   // just escape non-ASCII characters before passing the string to the hasher
   string = goog.string.escapeString(string);

   var hasher = new goog.crypt.Md5();
   hasher.reset();
   hasher.update(string);
   return goog.crypt.byteArrayToHex(hasher.digest());
}
```

**Comment by shicks** [comment] 2017-04-07 19:58
Looks like the problem is on line 168, where we assume that each character is a byte and we OR together four characters (left-shifted 0, 8, 16, and 24 bits).  For the first three characters in each quad, this means we get the wrong result, since we've OR'd the high byte of one character into the low byte of the next character.  For the fourth, the high byte is simply dropped.

I can imagine two reasonable fixes, not sure which is better (or importantly, more correct):
1. Treat the string as proper UTF-8, with multi-byte characters actually taking up multiple bytes in the buffer.  This will presumably come with a performance hit across the board.
2. Treat the string as UTF-16 (which is more consistent with how JS treats strings internally, IIUC), inserting padding bytes next to every single-byte character.  This changes the hash for all existing strings.

And a wrong fix would be to rotate the high byte of the fourth character into the low byte and XOR instead of OR.  But I'm pretty sure this would result in other collisions, so (without confirming this) I'm not going to consider it as a viable alternative, though it's the easiest.

**Comment by shicks** [comment] 2017-04-07 22:10
Looking further, this is a problem with most or all of our hash implementations.  I had hoped to simply deal with higher characters only when we see them, but since this logic would have to be replicated across many files, we'll probably want a separate utility function/class.  Simplest would be to just immediately transform all strings into a UTF-8 array, but that's going to be a performance hit.  Another option is to create a wrapper class to do it lazily (though checking the length is still going to be expensive up-front).

(Brainstorming here...) Potentially we could abstract this across all types with a ByteSource class.  The exact length isn't strictly needed, so we could afford to be fuzzy about it until we reach the end of the string, but that's a pretty crummy API.  What we really need is a way to request entire blocks at a time.  The optimization for compressing a block-at-a-time may be unnecessary if the wrapper can just read bytes in place - the main problem would be how to handle incomplete blocks.

In any case, Hash.prototype.update *does* specify that strings need to have only single-byte characters.  It might be reasonable to throw if we encounter higher characters, though there's a lot of places we'd need to check (across a lot of files) so I'm not sure it's worth it.  I might take a look at Guava's ByteSource API and see if we can take some inspiration from that.

**Comment by shicks** [comment] 2024-08-01 20:44
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.

**Closed by shicks** 2024-08-01 20:45 UTC
Labels: sunset
