### ISSUE TITLE
ClosureBuilder fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#30] opened 2014-04-15 03:12 UTC
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=603

**Comment by joeltine** [comment] 2015-07-20 23:10
Duplicate of #118

**Closed by joeltine** 2015-07-20 23:10 UTC
