### ISSUE TITLE
Filtered Menu Scroll bar issue

### ISSUE THREAD

**Issue by deyrajiv** [google/closure-library#1068] opened 2020-03-24 13:35 UTC
Hi,

I am using Filtered menu for one of my requirement. I experienced a weird behavior. If the list of the menu item is long scroll bar is visible but when user drags the scroll bar down such that filter label is not visible and releases the scroll bar to select an item the scroll bar moves up to set the focus to filter label( filter input).

**Comment by shicks** [comment] 2020-03-28 04:55
I took a look at the demos page and I'm not able to reproduce this.  Can you give more specifics, like which browser you're using, and which element has the scroll bar?  A complete minimal repro would be ideal.

(My attempt was to shrink the window and blow up the font so that a filtered view would still overflow the page - thus the scroll bar was on the BODY element - but I found the scrolling the entire page did not have any problems, and releasing the scroll bar did not move the focus).

**Comment by shicks** [comment] 2020-04-06 21:27
Mirroring the comment our goog.ui maintainer made on the internal issue:

> goog.ui is in maintenance mode and we're not fixing minor issues anymore.

If you send a PR we can consider merging it, but there's currently no active owner internally that can address this.

**Comment by shicks** [comment] 2024-08-01 20:48
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.

**Closed by shicks** 2024-08-01 20:48 UTC
Labels: P3 - PRs Only, sunset
