### ISSUE TITLE
goog.History/EventType.NAVIGATE sets token at different point depending on whether hash is set directly or through setToken

### ISSUE THREAD

**Issue by thedavidmeister** [google/closure-library#825] opened 2017-05-20 05:03 UTC
Just messing around with this in clojurescript.

Monitoring code:

```clojure
(let [history (History.)]
   (goog.events/listen history goog.History/EventType.NAVIGATE
    (fn [e]
     (prn (.-token e)))))
```

Case A:
set the hash directly

```clojure
(-> js/window .-location .-hash (set! "foo")) ; "" is printed
(prn (-> js/window .-location .-hash)) ; "foo" is printed
```

Case B:
use setToken

```clojure
(.setToken history "foo") ; "foo" is printed
(prn (-> js/window .-location .-hash)) ; "foo" is printed
```

I expect to see `"foo"` printed from the monitoring code both times, but it only seems to work for `.setToken`

**Comment by shicks** [comment] 2017-05-20 16:53
Is the clojurescript essential to this question? I'm pretty baffled by the
seemingly random dots, slashes, and hyphens. Can you post the generated JS
- does that possibly reveal what's going on?

**Comment by thedavidmeister** [comment] 2017-05-21 03:19
uh, it's just the example i had on hand, and i haven't done much JS lately sorry >.<

The syntax is just interop so should be nearly 1:1 with JS.

http://www.spacjer.com/blog/2014/09/12/clojurescript-javascript-interop/

I don't have the generated output but if i translate by hand it should look something like this:

Monitoring code:
```
var history = new History();
goog.events.listen(history, goog.History.EventType.NAVIGATE, function(e) { console.log(e.token); });
```

Case A:
```
window.location.hash = "foo"; // "" is logged
console.log(window.location.hash); // "foo" is logged
```

Case B:
```
history.setToken("foo"); // "foo" is logged
console.log(window.location.hash); // "foo" is logged
```

**Comment by thedavidmeister** [comment] 2017-05-21 03:23
The point is that the callback function in the monitoring code, for the `NAVIGATE` event, sometimes sees an empty string instead of `"foo"`, on the `token` property of the event.

Based on the tests I wrote, this seems to be reproducible, and dependant on whether the location hash is set directly in vanilla JS or via the `setToken` method.

Immediately after the event, the value of `window.location.hash` is identical in both cases, it's just a matter of what is available to the event callback.

**Comment by shicks** [comment] 2017-05-22 22:19
Not sure quite what's going on here.  I tried to repro locally but (a) `history` is a read-only property of the global object.  Is your constructor call the builtin `History` or `goog.History`?  If the latter, then I'm not able to repro - I get "foo" logged everywhere as expected.  If the former, then there's various other issues: Chrome tells me

```
var h = new History()
VM566:1 Uncaught TypeError: Illegal constructor
    at <anonymous>:1:9
```

so it doesn't even let me instantiate it.  If I just use the global `history` object, it still doesn't work:

```
goog.events.listen(history, goog.History.EventType.NAVIGATE, () => {});
events.js:264 Uncaught Error: addEventListener and attachEvent are unavailable.
    at Object.goog.events.listen_ (events.js:264)
    at Object.goog.events.listen (events.js:185)
    at <anonymous>:1:13
goog.events.listen_ @ events.js:264
goog.events.listen @ events.js:185
(anonymous) @ VM675:1
```

because `history` isn't an event target, so it doesn't have an `addEventListener` method.

Can you provide some more details?  What browser?  A specific `.js` file that I can run to reproduce the error on that browser?

**Comment by shicks** [comment] 2024-08-01 20:45
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.

**Closed by shicks** 2024-08-01 20:45 UTC
Labels: sunset
