### ISSUE TITLE
https://google.github.io/closure-library/api/ is broken

### ISSUE THREAD

**Issue by robert-stuttaford** [google/closure-library#893] opened 2018-03-30 10:16 UTC
Clicking on references to classes or namespaces is broken:

`Uncaught TypeError: Cannot assign to read only property '0' of string 'g'`

**Comment by jplaisted** [comment] 2018-04-05 17:56
Duplicate of #856

I've thus far been unable to reproduce. Having set repro steps would help.

**Closed by jplaisted** 2018-04-05 17:56 UTC
