### ISSUE TITLE
ModalPopup positioning causes display glitch

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#90] opened 2014-04-15 03:12 UTC
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=514

**Comment by joeltine** [comment] 2015-08-19 17:52
From original report:

1. Have an even viewSize.width & viewSize.height 
2. Use Google Chrome Version 23.0.1271.52 beta on Ubuntu 12.10
3. Display a ui.Dialog

What is the expected output? 
The dialog should show fine

What do you see instead?
There is a blank space between the border and the dialog (see attached picture)

What version of the product are you using? 
svn revision 2309

On what operating system?
Ubuntu 12.10

Please provide any additional information below.
This is caused by the .5px of the positioning (top & left) - see attached screenshot.

Digging into the code I have noticed that goog.style.setPosition() uses rounded values but for Gecko only - see goog.style.getPixelStyleValue_().

I guess Math.round() is avoided for speed reasons ? 

If this is the case, isn't computing buggyGeckoSubPixelPos (in setPosition) time consuming ? May be the compiler is able to "cache" the result ?

**Comment by joeltine** [comment] 2015-08-19 17:53
Screenshot:
![glitch](https://cloud.githubusercontent.com/assets/13138272/9364290/7537ed50-4660-11e5-9dbf-22a212e660cd.png)

**Comment by shicks** [comment] 2024-08-01 20:30
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.

**Closed by shicks** 2024-08-01 20:30 UTC
Labels: UI, P4 - Tracking Only, sunset
